all:
  hosts:
    atom:
      ansible_host: 185.242.112.107
    mail:
      ansible_host: 185.242.112.147
      public_ip: 185.242.112.147
      ispmail_fqdn: mail.rackmonkey.de
    web:
      ansible_host: 185.242.112.148
    monitoring:
      ansible_host: 185.242.112.149
      influx_databases:
      - monitoring
      grafana_datasources:
      - { db: monitoring, name: monitoring }
      grafana_admin_user: admin
  # for all
  vars:
    gateway: 185.242.112.1
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
    ssh_key_files:
      - public_keys/bauer-bauer
      - public_keys/bauer-zerbrechlich
    borg_retention_policy:
      keep_hourly: 3
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
