---

- name: add users
  include: user.yml user="{{ loop_user }}"
  with_items: '{{ users }}'
  loop_control:
    loop_var: loop_user
  when: not "{{ loop_user }}" == "root"

- name: set root password
  user: 
    name: root
    password: "{{ vault_root_password }} | password_hash('sha512')"

- name: Disable Password Authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PasswordAuthentication'
    line="PasswordAuthentication no"
    state=present
    backup=yes

- name: restart ssh
  service:
    name=sshd
    state=restarted
  when: "{{ restart_ssh }}"